# Generated by Django 5.2.14 on 2026-05-17 14:19

import django.db.models.deletion
import survivors.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetentionFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="اسم الفرع/المركز"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "branch_number",
                    models.CharField(
                        blank=True,
                        help_text="مثل: 215، 235، 251 ...",
                        max_length=20,
                        verbose_name="رقم الفرع (إن وُجد)",
                    ),
                ),
                (
                    "parent_entity",
                    models.CharField(
                        choices=[
                            ("military_intel", "المخابرات العسكرية"),
                            ("air_force_intel", "المخابرات الجوية"),
                            ("general_intel", "المخابرات العامة (أمن الدولة)"),
                            ("political_sec", "الأمن السياسي"),
                            ("military_police", "الشرطة العسكرية"),
                            ("prisons_dept", "إدارة السجون"),
                            ("other", "جهة أخرى"),
                        ],
                        max_length=30,
                        verbose_name="الجهة الأم",
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المحافظة"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="الموقع/العنوان"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="خط العرض",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="خط الطول",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
            ],
            options={
                "verbose_name": "مركز احتجاز",
                "verbose_name_plural": "مراكز الاحتجاز",
                "ordering": ["parent_entity", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="TortureMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(max_length=200, verbose_name="الاسم بالعربية"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("physical", "جسدي"),
                            ("psychological", "نفسي"),
                            ("sexual", "جنسي"),
                            ("environmental", "ظرفي/بيئي"),
                            ("deprivation", "حرمان (طعام، نوم، علاج)"),
                        ],
                        max_length=20,
                        verbose_name="الفئة",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
            ],
            options={
                "verbose_name": "نمط تعذيب",
                "verbose_name_plural": "أنماط التعذيب",
                "ordering": ["category", "name_ar"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence_number",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1 = المقابلة الأولى، 2 = الثانية...",
                        verbose_name="رقم المقابلة",
                    ),
                ),
                (
                    "is_first",
                    models.BooleanField(
                        default=True, verbose_name="هل هذه المقابلة الأولى للناجي؟"
                    ),
                ),
                (
                    "interview_date",
                    models.DateField(db_index=True, verbose_name="تاريخ المقابلة"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="المدة بالدقائق"
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("office", "في مكاتب الجمعية"),
                            ("survivor_home", "في منزل الناجي"),
                            ("remote", "عن بُعد (Zoom/Skype...)"),
                            ("phone", "هاتفية"),
                            ("field", "ميدانية أخرى"),
                            ("other", "أخرى"),
                        ],
                        default="office",
                        max_length=20,
                        verbose_name="نوع المكان",
                    ),
                ),
                (
                    "location_detail",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="تفاصيل المكان"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ar", "العربية - الفصحى"),
                            ("ar_levantine", "العربية - الشامية"),
                            ("ku", "الكردية"),
                            ("en", "الإنجليزية"),
                            ("tr", "التركية"),
                            ("de", "الألمانية"),
                            ("fr", "الفرنسية"),
                            ("other", "أخرى"),
                        ],
                        default="ar_levantine",
                        max_length=20,
                        verbose_name="لغة المقابلة",
                    ),
                ),
                (
                    "methodology",
                    models.CharField(
                        choices=[
                            ("istanbul", "بروتوكول إسطنبول"),
                            ("semi_structured", "شبه منظمة"),
                            ("narrative", "سردية مفتوحة"),
                            ("structured", "استمارة منظمة"),
                            ("follow_up", "مقابلة متابعة"),
                            ("other", "أخرى"),
                        ],
                        default="istanbul",
                        max_length=20,
                        verbose_name="المنهجية المتّبعة",
                    ),
                ),
                (
                    "recorded",
                    models.BooleanField(default=False, verbose_name="مسجَّلة"),
                ),
                (
                    "consent_to_record",
                    models.BooleanField(
                        default=False, verbose_name="موافقة على التسجيل"
                    ),
                ),
                (
                    "consent_to_publish_recording",
                    models.BooleanField(
                        default=False, verbose_name="موافقة على نشر التسجيل"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="ملخص ما تم تناوله في هذه الجلسة تحديداً",
                        verbose_name="ملخص المقابلة",
                    ),
                ),
                (
                    "gender_appropriate",
                    models.BooleanField(
                        default=False,
                        verbose_name="روعيت اعتبارات النوع الاجتماعي (محاوِرة لناجية مثلاً)",
                    ),
                ),
                (
                    "psychological_referral_after",
                    models.BooleanField(
                        default=False, verbose_name="أُحيلت لدعم نفسي بعد المقابلة"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات إضافية")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المحاوِر",
                    ),
                ),
                (
                    "note_taker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="note_taken_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدوِّن الملاحظات",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقابلة",
                "verbose_name_plural": "المقابلات",
                "ordering": ["survivor", "sequence_number", "interview_date"],
            },
        ),
        migrations.CreateModel(
            name="InterviewMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "فيديو"),
                            ("audio", "صوت"),
                            ("transcript", "نص حرفي (Transcript)"),
                            ("summary_doc", "مستند ملخص"),
                            ("photo", "صورة"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع الوسيط",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "file",
                    models.FileField(
                        upload_to=survivors.models.interview_media_path,
                        verbose_name="الملف",
                    ),
                ),
                (
                    "file_hash_sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="بصمة SHA-256"
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="حجم الملف"
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="المدة بالثواني (للفيديو/الصوت)",
                    ),
                ),
                (
                    "part_number",
                    models.PositiveIntegerField(
                        default=1,
                        verbose_name="رقم الجزء (إن كانت المقابلة مقسّمة لأكثر من ملف)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="وصف")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="survivors.interview",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="رفعه",
                    ),
                ),
            ],
            options={
                "verbose_name": "وسيط مقابلة",
                "verbose_name_plural": "وسائط المقابلات",
                "ordering": ["interview", "part_number", "media_type"],
            },
        ),
        migrations.CreateModel(
            name="SupportingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("official_regime", "وثيقة رسمية من جهة سورية"),
                            ("court_document", "وثيقة قضائية (محكمة عسكرية/ميدانية)"),
                            ("arrest_warrant", "أمر اعتقال"),
                            ("release_order", "أمر إفراج"),
                            ("transfer_order", "أمر إحالة/نقل"),
                            ("international_court", "وثيقة من محكمة دولية/IIIM"),
                            ("leaked", "وثيقة مسرّبة (قيصر، تسريبات الفروع...)"),
                            ("family_visit", "كرت زيارة/إيصال زيارة"),
                            ("family_remittance", "حوالة مالية للسجن"),
                            ("lawyer", "وثيقة من محامٍ"),
                            ("media", "مادة إعلامية"),
                            ("social_media", "منشور وسائل تواصل"),
                            ("photo", "صورة فوتوغرافية"),
                            ("video", "فيديو"),
                            ("audio", "تسجيل صوتي"),
                            ("other", "أخرى"),
                        ],
                        max_length=30,
                        verbose_name="نوع الوثيقة",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="عنوان الوثيقة"),
                ),
                ("description", models.TextField(verbose_name="الوصف والمحتوى")),
                (
                    "file",
                    models.FileField(
                        upload_to=survivors.models.document_upload_path,
                        verbose_name="الملف",
                    ),
                ),
                (
                    "file_hash_sha256",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="بصمة SHA-256 (Chain of Custody)",
                    ),
                ),
                (
                    "file_size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="حجم الملف"
                    ),
                ),
                (
                    "source_description",
                    models.TextField(
                        help_text="سلسلة الحيازة الكاملة - مَن، متى، أين، كيف",
                        verbose_name="مصدر الوثيقة وكيفية الحصول عليها",
                    ),
                ),
                ("date_obtained", models.DateField(verbose_name="تاريخ الاستلام")),
                (
                    "original_url",
                    models.URLField(blank=True, verbose_name="الرابط الأصلي"),
                ),
                (
                    "url_archived_at",
                    models.URLField(
                        blank=True, verbose_name="نسخة مؤرشفة (Archive.org)"
                    ),
                ),
                (
                    "access_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ ووقت الوصول"
                    ),
                ),
                (
                    "metadata_verified",
                    models.BooleanField(
                        default=False, verbose_name="تم التحقق من الميتاداتا"
                    ),
                ),
                (
                    "forensic_analysis",
                    models.TextField(
                        blank=True, verbose_name="التحليل الجنائي/التقني (إن وُجد)"
                    ),
                ),
                (
                    "document_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الوثيقة نفسها"
                    ),
                ),
                (
                    "document_reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الرقم المرجعي للوثيقة"
                    ),
                ),
                (
                    "issuing_authority",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الجهة المُصدرة"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "obtained_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="obtained_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="استلمها",
                    ),
                ),
            ],
            options={
                "verbose_name": "وثيقة داعمة",
                "verbose_name_plural": "الوثائق الداعمة",
                "ordering": ["-date_obtained"],
            },
        ),
        migrations.CreateModel(
            name="ChainOfCustodyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("collected", "استلام"),
                            ("transferred", "نقل ليد أخرى"),
                            ("accessed", "اطلاع"),
                            ("copied", "نسخ"),
                            ("shared_external", "مشاركة مع جهة خارجية"),
                            ("archived", "أرشفة"),
                            ("verified", "تحقق"),
                        ],
                        max_length=30,
                        verbose_name="الإجراء",
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="المُستلِم (الشخص/الجهة)",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="الوقت"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="المكان"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "signature_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="custody/signatures/",
                        verbose_name="توقيع (إن وُجد)",
                    ),
                ),
                (
                    "by_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نفّذه",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custody_log",
                        to="survivors.supportingdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل سلسلة حيازة",
                "verbose_name_plural": "سجلات سلسلة الحيازة",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SurvivorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="الرقم المرجعي",
                    ),
                ),
                (
                    "case_reference",
                    models.CharField(
                        help_text="مثال: HQ-2025-0001",
                        max_length=50,
                        unique=True,
                        verbose_name="رقم القضية الداخلي",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "father_name",
                    models.CharField(max_length=100, verbose_name="اسم الأب"),
                ),
                (
                    "grandfather_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم الجد"
                    ),
                ),
                (
                    "family_name",
                    models.CharField(max_length=100, verbose_name="اسم العائلة"),
                ),
                (
                    "mother_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الأم"
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="أي أسماء مستعارة أو كنى عُرف بها",
                        max_length=100,
                        verbose_name="الكنية/اللقب",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        verbose_name="الرقم الوطني السوري",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "birth_date_approximate",
                    models.BooleanField(
                        default=False, verbose_name="تاريخ الميلاد تقريبي"
                    ),
                ),
                (
                    "birth_governorate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("damascus", "دمشق"),
                            ("rural_damascus", "ريف دمشق"),
                            ("aleppo", "حلب"),
                            ("homs", "حمص"),
                            ("hama", "حماة"),
                            ("latakia", "اللاذقية"),
                            ("tartus", "طرطوس"),
                            ("idlib", "إدلب"),
                            ("daraa", "درعا"),
                            ("suwayda", "السويداء"),
                            ("quneitra", "القنيطرة"),
                            ("raqqa", "الرقة"),
                            ("deir_ez_zor", "دير الزور"),
                            ("hasakah", "الحسكة"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="محافظة الولادة",
                    ),
                ),
                (
                    "birth_place_detail",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="مكان الولادة - تفصيلي (مدينة، قرية، حي)",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "ذكر"),
                            ("female", "أنثى"),
                            ("other", "آخر/لا يصرّح"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="سورية", max_length=100, verbose_name="الجنسية"
                    ),
                ),
                (
                    "marital_status_at_detention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "أعزب/عزباء"),
                            ("engaged", "مخطوب/ة"),
                            ("married", "متزوج/ة"),
                            ("divorced", "مطلّق/ة"),
                            ("widowed", "أرمل/أرملة"),
                            ("separated", "منفصل/ة"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="الحالة الزوجية وقت الاعتقال",
                    ),
                ),
                (
                    "address_at_detention",
                    models.TextField(
                        blank=True, verbose_name="عنوان السكن وقت الاعتقال"
                    ),
                ),
                (
                    "governorate_at_detention",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("damascus", "دمشق"),
                            ("rural_damascus", "ريف دمشق"),
                            ("aleppo", "حلب"),
                            ("homs", "حمص"),
                            ("hama", "حماة"),
                            ("latakia", "اللاذقية"),
                            ("tartus", "طرطوس"),
                            ("idlib", "إدلب"),
                            ("daraa", "درعا"),
                            ("suwayda", "السويداء"),
                            ("quneitra", "القنيطرة"),
                            ("raqqa", "الرقة"),
                            ("deir_ez_zor", "دير الزور"),
                            ("hasakah", "الحسكة"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="المحافظة وقت الاعتقال",
                    ),
                ),
                (
                    "occupation_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student_school", "طالب مدرسي"),
                            ("student_university", "طالب جامعي"),
                            ("teacher", "معلم/أستاذ"),
                            ("doctor", "طبيب"),
                            ("nurse", "ممرض/ة"),
                            ("lawyer", "محامي"),
                            ("engineer", "مهندس"),
                            ("journalist", "صحفي/إعلامي"),
                            ("activist", "ناشط حقوقي/إنساني"),
                            ("civil_servant", "موظف حكومي"),
                            ("military", "عسكري/أمني"),
                            ("merchant", "تاجر/صاحب عمل"),
                            ("worker", "عامل"),
                            ("farmer", "مزارع"),
                            ("driver", "سائق"),
                            ("housewife", "ربّة منزل"),
                            ("religious", "رجل دين/إمام"),
                            ("artist", "فنان/مبدع"),
                            ("unemployed", "بدون عمل"),
                            ("retired", "متقاعد"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="فئة العمل/الدراسة وقت الاعتقال",
                    ),
                ),
                (
                    "occupation_detail",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="تفاصيل العمل (اختياري)",
                    ),
                ),
                (
                    "political_activity_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("peaceful_protest", "نشاط احتجاجي سلمي"),
                            ("media_activism", "نشاط إعلامي/توثيقي"),
                            ("humanitarian", "عمل إنساني/إغاثي"),
                            ("medical_aid", "إسعاف/علاج للجرحى"),
                            ("political_party", "منتسب لحزب سياسي معارض"),
                            ("armed_group_fsa", "الجيش الحر"),
                            ("armed_group_other", "فصيل مسلح آخر"),
                            ("civil_society", "منظمة مجتمع مدني"),
                            ("religious_oppose", "معارضة على خلفية دينية"),
                            ("kurdish_political", "نشاط سياسي كردي"),
                            ("no_activity", "لا نشاط سياسي - اعتقال عشوائي"),
                            ("relative_of", "بسبب قرابة لشخص آخر"),
                            ("unknown_reason", "السبب غير معلوم"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="فئة النشاط/الانتماء السياسي",
                    ),
                ),
                (
                    "political_activity_detail",
                    models.TextField(
                        blank=True, verbose_name="تفاصيل النشاط السياسي (اختياري)"
                    ),
                ),
                (
                    "current_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="رقم الهاتف الحالي"
                    ),
                ),
                (
                    "current_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="البريد الإلكتروني الحالي",
                    ),
                ),
                (
                    "current_country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SY", "سوريا"),
                            ("TR", "تركيا"),
                            ("LB", "لبنان"),
                            ("JO", "الأردن"),
                            ("IQ", "العراق"),
                            ("EG", "مصر"),
                            ("DE", "ألمانيا"),
                            ("NL", "هولندا"),
                            ("SE", "السويد"),
                            ("FR", "فرنسا"),
                            ("GB", "بريطانيا"),
                            ("AT", "النمسا"),
                            ("BE", "بلجيكا"),
                            ("DK", "الدنمارك"),
                            ("NO", "النرويج"),
                            ("US", "الولايات المتحدة"),
                            ("CA", "كندا"),
                            ("SA", "السعودية"),
                            ("AE", "الإمارات"),
                            ("QA", "قطر"),
                            ("KW", "الكويت"),
                            ("OTHER", "أخرى"),
                        ],
                        db_index=True,
                        max_length=10,
                        verbose_name="بلد الإقامة الحالي",
                    ),
                ),
                (
                    "current_governorate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("damascus", "دمشق"),
                            ("rural_damascus", "ريف دمشق"),
                            ("aleppo", "حلب"),
                            ("homs", "حمص"),
                            ("hama", "حماة"),
                            ("latakia", "اللاذقية"),
                            ("tartus", "طرطوس"),
                            ("idlib", "إدلب"),
                            ("daraa", "درعا"),
                            ("suwayda", "السويداء"),
                            ("quneitra", "القنيطرة"),
                            ("raqqa", "الرقة"),
                            ("deir_ez_zor", "دير الزور"),
                            ("hasakah", "الحسكة"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="المحافظة الحالية (داخل سوريا)",
                    ),
                ),
                (
                    "current_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="المدينة/البلدة الحالية",
                    ),
                ),
                (
                    "next_of_kin_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم قريب للتواصل"
                    ),
                ),
                (
                    "next_of_kin_relation",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="صلة القرابة"
                    ),
                ),
                (
                    "next_of_kin_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="رقم القريب"
                    ),
                ),
                (
                    "photo_recent",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="survivors/photos/recent/",
                        verbose_name="صورة حديثة",
                    ),
                ),
                (
                    "photo_before_detention",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="survivors/photos/before/",
                        verbose_name="صورة قبل الاعتقال",
                    ),
                ),
                (
                    "file_classification",
                    models.CharField(
                        choices=[
                            ("A", "فئة A - جاهز للمحاكم الدولية"),
                            ("B", "فئة B - جاهز للـIIIM ولجنة التحقيق"),
                            ("C", "فئة C - أرشيف/إحصاء فقط"),
                            ("draft", "مسودة - قيد الجمع"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                        verbose_name="تصنيف الملف",
                    ),
                ),
                (
                    "reliability_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="درجة الموثوقية (0-5) - محسوبة آلياً",
                    ),
                ),
                (
                    "corroboration_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="درجة التحقق المتقاطع (0-5) - محسوبة آلياً",
                    ),
                ),
                (
                    "completeness_score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        editable=False,
                        verbose_name="درجة الاكتمال (0-5) - محسوبة آلياً",
                    ),
                ),
                (
                    "medical_referral_offered",
                    models.BooleanField(
                        default=False, verbose_name="هل عُرضت إحالة طبية؟"
                    ),
                ),
                (
                    "psychological_referral_offered",
                    models.BooleanField(
                        default=False, verbose_name="هل عُرضت إحالة نفسية؟"
                    ),
                ),
                (
                    "legal_aid_offered",
                    models.BooleanField(
                        default=False, verbose_name="هل عُرضت مساعدة قانونية؟"
                    ),
                ),
                (
                    "referral_notes",
                    models.TextField(blank=True, verbose_name="تفاصيل الإحالات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "documenter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documented_survivors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموثّق المسؤول",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملف ناجٍ",
                "verbose_name_plural": "ملفات الناجين",
                "ordering": ["-created_at"],
                "permissions": [
                    ("view_sensitive_data", "Can view sensitive identifying data"),
                    ("export_files", "Can export survivor files to external bodies"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SurvivorNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "ملاحظة عامة"),
                            ("follow_up", "متابعة"),
                            ("referral", "إحالة"),
                            ("medical", "طبية/نفسية"),
                            ("legal", "قانونية"),
                            ("security", "أمنية/حماية"),
                            ("family", "متعلقة بالعائلة"),
                            ("inconsistency", "ملاحظة على اتساق الرواية"),
                            ("verification", "تحقق من معلومة"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                        verbose_name="نوع الملاحظة",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان مختصر"
                    ),
                ),
                ("content", models.TextField(verbose_name="الملاحظة")),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, verbose_name="مثبّتة في أعلى الملف"
                    ),
                ),
                (
                    "is_confidential",
                    models.BooleanField(
                        default=False, verbose_name="سرّية (للمشرفين فقط)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُحرِّر",
                    ),
                ),
                (
                    "survivor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="survivors.survivorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة",
                "verbose_name_plural": "الملاحظات",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="supportingdocument",
            name="survivor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="survivors.survivorprofile",
            ),
        ),
        migrations.CreateModel(
            name="ReleaseEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("release_date", models.DateField(verbose_name="تاريخ الإفراج")),
                (
                    "release_type",
                    models.CharField(
                        choices=[
                            ("unconditional", "إفراج غير مشروط"),
                            ("conditional", "إفراج مشروط"),
                            ("amnesty", "عفو عام"),
                            ("settlement", "تسوية وضع"),
                            ("bribe", "بدفع رشوة"),
                            ("exchange", "تبادل/صفقة"),
                            ("escape", "فرار"),
                            ("transfer_out", "نقل لجهة أخرى"),
                            ("unknown", "غير معلوم"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإفراج",
                    ),
                ),
                (
                    "release_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="مكان الإفراج"
                    ),
                ),
                (
                    "bribe_amount",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="قيمة الرشوة (إن وُجدت)",
                    ),
                ),
                (
                    "conditions",
                    models.TextField(blank=True, verbose_name="شروط الإفراج"),
                ),
                ("circumstances", models.TextField(verbose_name="ظروف الإفراج")),
                (
                    "survivor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_event",
                        to="survivors.survivorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "واقعة إفراج",
                "verbose_name_plural": "وقائع الإفراج",
            },
        ),
        migrations.CreateModel(
            name="MedicalAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("physical", "جسدي"),
                            ("psychological", "نفسي"),
                            ("comprehensive", "شامل"),
                        ],
                        max_length=20,
                        verbose_name="نوع التقييم",
                    ),
                ),
                ("assessment_date", models.DateField(verbose_name="تاريخ التقييم")),
                (
                    "assessor_name",
                    models.CharField(max_length=200, verbose_name="اسم الفاحص"),
                ),
                (
                    "assessor_credentials",
                    models.CharField(max_length=300, verbose_name="المؤهلات والاختصاص"),
                ),
                (
                    "assessor_organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="المنظمة (مثل LDHR)"
                    ),
                ),
                (
                    "istanbul_protocol_compliant",
                    models.BooleanField(
                        default=False, verbose_name="متوافق مع بروتوكول إسطنبول"
                    ),
                ),
                (
                    "physical_findings",
                    models.TextField(blank=True, verbose_name="النتائج الجسدية"),
                ),
                (
                    "scars_description",
                    models.TextField(blank=True, verbose_name="وصف الندوب والإصابات"),
                ),
                (
                    "disabilities",
                    models.TextField(blank=True, verbose_name="الإعاقات المكتسبة"),
                ),
                (
                    "psychological_findings",
                    models.TextField(blank=True, verbose_name="النتائج النفسية"),
                ),
                (
                    "ptsd_indicators",
                    models.BooleanField(
                        default=False, verbose_name="علامات اضطراب ما بعد الصدمة"
                    ),
                ),
                (
                    "depression_indicators",
                    models.BooleanField(default=False, verbose_name="علامات اكتئاب"),
                ),
                (
                    "anxiety_indicators",
                    models.BooleanField(default=False, verbose_name="علامات قلق"),
                ),
                (
                    "consistency_with_account",
                    models.TextField(
                        blank=True,
                        help_text="بمصطلحات بروتوكول إسطنبول: highly consistent / consistent / typical / not consistent",
                        verbose_name="مدى توافق النتائج مع رواية الناجي",
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="survivors/medical/",
                        verbose_name="ملف التقرير",
                    ),
                ),
                (
                    "consent_to_share",
                    models.BooleanField(
                        default=False, verbose_name="موافقة على مشاركة التقرير"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survivor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_assessments",
                        to="survivors.survivorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم طبي",
                "verbose_name_plural": "التقييمات الطبية",
                "ordering": ["-assessment_date"],
            },
        ),
        migrations.CreateModel(
            name="LongTermImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "physical_injuries_permanent",
                    models.TextField(blank=True, verbose_name="إصابات جسدية دائمة"),
                ),
                (
                    "chronic_illnesses",
                    models.TextField(blank=True, verbose_name="أمراض مزمنة ناتجة"),
                ),
                ("disabilities", models.TextField(blank=True, verbose_name="إعاقات")),
                (
                    "psychological_symptoms",
                    models.TextField(blank=True, verbose_name="الأعراض النفسية"),
                ),
                (
                    "sleep_disorders",
                    models.BooleanField(default=False, verbose_name="اضطرابات نوم"),
                ),
                (
                    "flashbacks",
                    models.BooleanField(default=False, verbose_name="استرجاع للذكريات"),
                ),
                (
                    "social_withdrawal",
                    models.BooleanField(default=False, verbose_name="انعزال اجتماعي"),
                ),
                (
                    "family_impact",
                    models.TextField(blank=True, verbose_name="الأثر على العائلة"),
                ),
                (
                    "work_impact",
                    models.TextField(
                        blank=True, verbose_name="الأثر على القدرة على العمل"
                    ),
                ),
                (
                    "education_impact",
                    models.TextField(blank=True, verbose_name="الأثر على التعليم"),
                ),
                (
                    "financial_impact",
                    models.TextField(blank=True, verbose_name="الأثر المالي"),
                ),
                (
                    "current_medications",
                    models.TextField(blank=True, verbose_name="الأدوية الحالية"),
                ),
                (
                    "receiving_treatment",
                    models.BooleanField(
                        default=False, verbose_name="يتلقى علاجاً حالياً"
                    ),
                ),
                (
                    "treatment_details",
                    models.TextField(blank=True, verbose_name="تفاصيل العلاج"),
                ),
                (
                    "survivor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="long_term_impact",
                        to="survivors.survivorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "أثر طويل الأمد",
                "verbose_name_plural": "الآثار طويلة الأمد",
            },
        ),
        migrations.AddField(
            model_name="interview",
            name="survivor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interviews",
                to="survivors.survivorprofile",
            ),
        ),
        migrations.CreateModel(
            name="InformedConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_documented",
                    models.BooleanField(
                        default=False, verbose_name="هل تم أخذ الموافقة المستنيرة؟"
                    ),
                ),
                (
                    "consent_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الموافقة"
                    ),
                ),
                (
                    "consent_witness",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="شاهد على الموافقة"
                    ),
                ),
                (
                    "consent_form_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="survivors/consent/",
                        verbose_name="نموذج الموافقة الموقّع (PDF/صورة)",
                    ),
                ),
                (
                    "share_with_iiim",
                    models.BooleanField(
                        default=False, verbose_name="مشاركة مع الـIIIM"
                    ),
                ),
                (
                    "share_with_coi",
                    models.BooleanField(
                        default=False, verbose_name="مشاركة مع لجنة التحقيق الأممية"
                    ),
                ),
                (
                    "share_with_icc",
                    models.BooleanField(
                        default=False, verbose_name="مشاركة مع المحكمة الجنائية الدولية"
                    ),
                ),
                (
                    "share_with_universal_jurisdiction",
                    models.BooleanField(
                        default=False,
                        verbose_name="مشاركة مع محاكم الولاية القضائية العالمية",
                    ),
                ),
                (
                    "share_with_partner_orgs",
                    models.BooleanField(
                        default=False, verbose_name="مشاركة مع منظمات شريكة"
                    ),
                ),
                (
                    "share_with_media",
                    models.BooleanField(
                        default=False, verbose_name="مشاركة مع الإعلام"
                    ),
                ),
                (
                    "share_publicly",
                    models.BooleanField(
                        default=False, verbose_name="نشر علني (تقارير، مواقع، إلخ)"
                    ),
                ),
                (
                    "anonymize_name",
                    models.BooleanField(default=False, verbose_name="إخفاء الاسم"),
                ),
                (
                    "anonymize_photo",
                    models.BooleanField(default=False, verbose_name="إخفاء الصورة"),
                ),
                (
                    "anonymize_location",
                    models.BooleanField(default=False, verbose_name="إخفاء الموقع"),
                ),
                (
                    "anonymize_family_details",
                    models.BooleanField(
                        default=False, verbose_name="إخفاء تفاصيل العائلة"
                    ),
                ),
                (
                    "withdrawal_right_explained",
                    models.BooleanField(default=False, verbose_name="شُرح حق الانسحاب"),
                ),
                (
                    "confidentiality_limits_explained",
                    models.BooleanField(
                        default=False, verbose_name="شُرحت حدود السرّية"
                    ),
                ),
                (
                    "intended_uses_explained",
                    models.BooleanField(
                        default=False, verbose_name="شُرحت الاستخدامات المحتملة"
                    ),
                ),
                (
                    "consent_withdrawn",
                    models.BooleanField(default=False, verbose_name="سُحبت الموافقة"),
                ),
                (
                    "withdrawal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ سحب الموافقة"
                    ),
                ),
                (
                    "withdrawal_reason",
                    models.TextField(blank=True, verbose_name="سبب السحب"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات إضافية")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "survivor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent",
                        to="survivors.survivorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "موافقة مستنيرة",
                "verbose_name_plural": "نماذج الموافقات المستنيرة",
            },
        ),
        migrations.CreateModel(
            name="DetentionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detention_date", models.DateField(verbose_name="تاريخ الاعتقال")),
                (
                    "date_approximate",
                    models.BooleanField(default=False, verbose_name="التاريخ تقريبي"),
                ),
                (
                    "detention_location",
                    models.CharField(
                        max_length=300,
                        verbose_name="مكان الاعتقال (شارع، نقطة تفتيش، البيت...)",
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المحافظة"
                    ),
                ),
                (
                    "arresting_entity",
                    models.CharField(
                        help_text="مثال: المخابرات الجوية - فرع التحقيق - المطار",
                        max_length=300,
                        verbose_name="الجهة المعتقِلة (الاسم الكامل)",
                    ),
                ),
                (
                    "arresting_personnel_details",
                    models.TextField(
                        blank=True,
                        verbose_name="أسماء/رتب/علامات مميزة لعناصر الاعتقال",
                    ),
                ),
                (
                    "reason_stated",
                    models.TextField(
                        blank=True, verbose_name="السبب المُعلَن (إن وُجد)"
                    ),
                ),
                (
                    "circumstances",
                    models.TextField(verbose_name="ظروف الاعتقال بالتفصيل"),
                ),
                (
                    "witnesses_to_arrest",
                    models.TextField(
                        blank=True,
                        verbose_name="شهود على الاعتقال (جيران، عابرو سبيل...)",
                    ),
                ),
                (
                    "family_notified",
                    models.BooleanField(
                        default=False, verbose_name="هل أُبلغت العائلة؟"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "survivor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detention_events",
                        to="survivors.survivorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "واقعة اعتقال",
                "verbose_name_plural": "وقائع الاعتقال",
                "ordering": ["detention_date"],
            },
        ),
        migrations.CreateModel(
            name="DetentionPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField(verbose_name="من تاريخ")),
                (
                    "from_date_approximate",
                    models.BooleanField(default=False, verbose_name="التاريخ تقريبي"),
                ),
                (
                    "to_date",
                    models.DateField(blank=True, null=True, verbose_name="إلى تاريخ"),
                ),
                (
                    "to_date_approximate",
                    models.BooleanField(default=False, verbose_name="التاريخ تقريبي"),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="لترتيب الفترات تصاعدياً",
                        verbose_name="ترتيب الفترة",
                    ),
                ),
                (
                    "cell_description",
                    models.TextField(
                        blank=True, verbose_name="وصف الزنزانة (حجمها، تهويتها...)"
                    ),
                ),
                (
                    "cellmates_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="عدد المحتجزين معه"
                    ),
                ),
                (
                    "food_water",
                    models.TextField(blank=True, verbose_name="الطعام والماء"),
                ),
                (
                    "sleep_conditions",
                    models.TextField(blank=True, verbose_name="ظروف النوم"),
                ),
                (
                    "hygiene_conditions",
                    models.TextField(blank=True, verbose_name="النظافة والحمّام"),
                ),
                (
                    "medical_care",
                    models.TextField(blank=True, verbose_name="الرعاية الطبية"),
                ),
                (
                    "contact_with_outside",
                    models.TextField(blank=True, verbose_name="التواصل مع الخارج"),
                ),
                (
                    "torture_description",
                    models.TextField(
                        blank=True,
                        help_text="بأقوال الناجي مباشرة قدر الإمكان",
                        verbose_name="وصف تفصيلي للتعذيب",
                    ),
                ),
                (
                    "sexual_violence_reported",
                    models.BooleanField(default=False, verbose_name="بلاغ عن عنف جنسي"),
                ),
                (
                    "sexual_violence_details",
                    models.TextField(
                        blank=True, verbose_name="تفاصيل العنف الجنسي (بحساسية)"
                    ),
                ),
                (
                    "witnessed_deaths",
                    models.TextField(
                        blank=True,
                        verbose_name="شهد على وفيات داخل المعتقل (أسماء، تواريخ، أوصاف)",
                    ),
                ),
                (
                    "witnessed_others",
                    models.TextField(
                        blank=True,
                        verbose_name="معتقلون آخرون شاهدهم وقد يكونون مصدر تأكيد",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات إضافية")),
                (
                    "detention_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periods",
                        to="survivors.detentionevent",
                        verbose_name="واقعة الاعتقال المرتبطة",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detention_periods",
                        to="survivors.detentionfacility",
                        verbose_name="مركز الاحتجاز",
                    ),
                ),
                (
                    "survivor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detention_periods",
                        to="survivors.survivorprofile",
                    ),
                ),
                (
                    "torture_methods",
                    models.ManyToManyField(
                        blank=True,
                        related_name="periods",
                        to="survivors.torturemethod",
                        verbose_name="أنماط التعذيب الموثَّقة",
                    ),
                ),
            ],
            options={
                "verbose_name": "فترة احتجاز",
                "verbose_name_plural": "فترات الاحتجاز",
                "ordering": ["survivor", "order_index", "from_date"],
            },
        ),
        migrations.CreateModel(
            name="Witness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "witness_name",
                    models.CharField(max_length=200, verbose_name="اسم الشاهد"),
                ),
                (
                    "witness_case_reference",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="رقم ملف الشاهد (إن كان موثقاً)",
                    ),
                ),
                (
                    "witness_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="هاتف الشاهد"
                    ),
                ),
                (
                    "witness_current_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الموقع الحالي للشاهد"
                    ),
                ),
                ("period_from", models.DateField(verbose_name="من تاريخ")),
                (
                    "period_to",
                    models.DateField(blank=True, null=True, verbose_name="إلى تاريخ"),
                ),
                (
                    "cell_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="رقم الزنزانة (إن وُجد)"
                    ),
                ),
                (
                    "how_recognized",
                    models.TextField(
                        verbose_name="كيف تعرّف عليه؟ (الاسم، الوجه، حادثة...)"
                    ),
                ),
                (
                    "distinguishing_details",
                    models.TextField(blank=True, verbose_name="تفاصيل مميزة لاحظها"),
                ),
                (
                    "specific_incidents",
                    models.TextField(blank=True, verbose_name="حوادث محددة شهدها"),
                ),
                (
                    "relationship_before",
                    models.CharField(
                        choices=[
                            ("stranger", "لم يكن يعرفه"),
                            ("acquaintance", "معرفة"),
                            ("friend", "صديق"),
                            ("relative", "قريب"),
                            ("colleague", "زميل عمل/دراسة"),
                        ],
                        default="stranger",
                        max_length=20,
                        verbose_name="علاقة الشاهد بالناجي قبل الاعتقال",
                    ),
                ),
                (
                    "is_independent",
                    models.BooleanField(
                        default=False,
                        verbose_name="شاهد مستقل (لم يلتقِ بالناجي بعد الإفراج قبل الإدلاء بشهادته)",
                    ),
                ),
                (
                    "met_after_release",
                    models.BooleanField(
                        default=False, verbose_name="التقيا بعد الإفراج"
                    ),
                ),
                (
                    "consent_to_use_testimony",
                    models.BooleanField(
                        default=False, verbose_name="موافقة الشاهد على استخدام شهادته"
                    ),
                ),
                (
                    "declaration_signed",
                    models.BooleanField(default=False, verbose_name="بيان موقّع"),
                ),
                (
                    "declaration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ البيان"
                    ),
                ),
                (
                    "declaration_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="survivors/declarations/",
                        verbose_name="ملف البيان الموقّع",
                    ),
                ),
                ("full_testimony", models.TextField(verbose_name="نص الشهادة الكامل")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "documenter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الموثّق الذي أخذ الشهادة",
                    ),
                ),
                (
                    "facility_witnessed_at",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="survivors.detentionfacility",
                        verbose_name="الفرع/المكان الذي رآه فيه",
                    ),
                ),
                (
                    "survivor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witnesses",
                        to="survivors.survivorprofile",
                        verbose_name="الناجي المُشهَد عليه",
                    ),
                ),
            ],
            options={
                "verbose_name": "شاهد",
                "verbose_name_plural": "الشهود",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="interview",
            unique_together={("survivor", "sequence_number")},
        ),
    ]
