# Generated by Django 5.2.14 on 2026-05-18 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survivors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalassessment",
            name="consistency_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات على التوافق"),
        ),
        migrations.AddField(
            model_name="survivorprofile",
            name="archive_reason",
            field=models.TextField(blank=True, verbose_name="سبب الأرشفة"),
        ),
        migrations.AddField(
            model_name="survivorprofile",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الأرشفة"
            ),
        ),
        migrations.AddField(
            model_name="survivorprofile",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_survivors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="أرشفه",
            ),
        ),
        migrations.AddField(
            model_name="survivorprofile",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="بدلاً من الحذف النهائي، نُؤرشف الملفات لحفظ الأدلة",
                verbose_name="مؤرشف",
            ),
        ),
        migrations.AlterField(
            model_name="medicalassessment",
            name="consistency_with_account",
            field=models.CharField(
                choices=[
                    ("not_assessed", "لم يُقَيَّم"),
                    ("not_consistent", "غير متوافق"),
                    ("consistent", "متوافق"),
                    ("highly_consistent", "متوافق بدرجة عالية"),
                    ("typical", "نمطي/مطابق تماماً"),
                    ("diagnostic", "تشخيصي - دليل قاطع"),
                ],
                default="not_assessed",
                help_text="التصنيف الإسطنبولي القياسي لمصداقية الإصابات",
                max_length=30,
                verbose_name="مدى توافق النتائج مع رواية الناجي",
            ),
        ),
        migrations.AlterField(
            model_name="supportingdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("official_regime", "وثيقة رسمية من جهة سورية"),
                    ("court_document", "وثيقة قضائية (محكمة عسكرية/ميدانية)"),
                    ("arrest_warrant", "أمر اعتقال"),
                    ("release_order", "أمر إفراج"),
                    ("transfer_order", "أمر إحالة/نقل"),
                    ("international_court", "وثيقة من محكمة دولية/IIIM"),
                    ("leaked", "وثيقة مسرّبة (قيصر، تسريبات الفروع...)"),
                    ("family_visit", "كرت زيارة/إيصال زيارة"),
                    ("family_remittance", "حوالة مالية للسجن"),
                    ("lawyer", "وثيقة من محامٍ"),
                    ("media", "مادة إعلامية"),
                    ("social_media", "منشور وسائل تواصل"),
                    ("photo", "صورة فوتوغرافية"),
                    ("video", "فيديو"),
                    ("audio", "تسجيل صوتي"),
                    ("other", "أخرى"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="نوع الوثيقة",
            ),
        ),
        migrations.AlterField(
            model_name="survivorprofile",
            name="national_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="11 رقم. يُسمح بالفراغ لكن إذا أُدخل، يجب أن يكون فريداً.",
                max_length=20,
                verbose_name="الرقم الوطني السوري",
            ),
        ),
    ]
