# Generated by Django 5.2.14 on 2026-05-17 14:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("documenter", "موثّق ميداني"),
                            ("supervisor", "مشرف توثيق"),
                            ("reviewer", "مدقّق/مراجع"),
                            ("protection", "ضابط حماية وأمن البيانات"),
                            ("admin", "مدير النظام"),
                            ("read_only", "اطلاع فقط"),
                        ],
                        default="documenter",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "full_name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم الكامل (عربي)"
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="المنظمة/الجمعية"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "confidentiality_agreement_signed",
                    models.BooleanField(
                        default=False, verbose_name="اتفاقية السرّية موقّعة"
                    ),
                ),
                (
                    "confidentiality_signed_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="تاريخ توقيع اتفاقية السرّية",
                    ),
                ),
                (
                    "training_istanbul_protocol",
                    models.BooleanField(
                        default=False, verbose_name="مدرَّب على بروتوكول إسطنبول"
                    ),
                ),
                (
                    "training_berkeley_protocol",
                    models.BooleanField(
                        default=False, verbose_name="مدرَّب على بروتوكول بيركلي"
                    ),
                ),
                (
                    "training_completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ إتمام التدريب"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("view", "اطلاع"),
                            ("create", "إنشاء"),
                            ("update", "تعديل"),
                            ("delete", "حذف"),
                            ("export", "تصدير"),
                            ("download", "تنزيل"),
                            ("login", "تسجيل دخول"),
                            ("logout", "تسجيل خروج"),
                            ("failed_login", "محاولة دخول فاشلة"),
                        ],
                        max_length=20,
                        verbose_name="الإجراء",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="نوع السجل"
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="معرّف السجل"
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="وصف السجل"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="عنوان IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="متصفح المستخدم"
                    ),
                ),
                (
                    "path",
                    models.CharField(blank=True, max_length=500, verbose_name="المسار"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="الوقت"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تدقيق",
                "verbose_name_plural": "سجلات التدقيق",
                "ordering": ["-timestamp"],
            },
        ),
    ]
