# Generated by Django 5.2.14 on 2026-05-17 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("survivors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "highest_level_before_detention",
                    models.CharField(
                        choices=[
                            ("illiterate", "أمي"),
                            ("reads_writes", "يقرأ ويكتب فقط"),
                            ("primary", "ابتدائي"),
                            ("preparatory", "إعدادي"),
                            ("secondary", "ثانوي/بكالوريا"),
                            ("vocational", "معهد متوسط/مهني"),
                            ("bachelor", "إجازة جامعية"),
                            ("master", "ماجستير"),
                            ("phd", "دكتوراه"),
                        ],
                        max_length=20,
                        verbose_name="أعلى مستوى دراسي قبل الاعتقال",
                    ),
                ),
                (
                    "highest_level_now",
                    models.CharField(
                        choices=[
                            ("illiterate", "أمي"),
                            ("reads_writes", "يقرأ ويكتب فقط"),
                            ("primary", "ابتدائي"),
                            ("preparatory", "إعدادي"),
                            ("secondary", "ثانوي/بكالوريا"),
                            ("vocational", "معهد متوسط/مهني"),
                            ("bachelor", "إجازة جامعية"),
                            ("master", "ماجستير"),
                            ("phd", "دكتوراه"),
                        ],
                        max_length=20,
                        verbose_name="أعلى مستوى دراسي حالياً",
                    ),
                ),
                (
                    "studies_interrupted_by_detention",
                    models.BooleanField(
                        default=False, verbose_name="هل انقطع عن الدراسة بسبب الاعتقال؟"
                    ),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=200, verbose_name="التخصص"),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="المؤسسة التعليمية"
                    ),
                ),
                (
                    "is_currently_studying",
                    models.BooleanField(default=False, verbose_name="هل يدرس حالياً؟"),
                ),
                (
                    "current_program",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="البرنامج/المرحلة الحالية",
                    ),
                ),
                (
                    "wants_to_resume",
                    models.BooleanField(
                        default=False, verbose_name="يرغب باستئناف التعليم"
                    ),
                ),
                (
                    "obstacles_to_education",
                    models.TextField(
                        blank=True, verbose_name="عقبات تحول دون استئناف التعليم"
                    ),
                ),
                (
                    "languages_spoken",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="اللغات التي يجيدها"
                    ),
                ),
                (
                    "has_certificates",
                    models.BooleanField(
                        default=False, verbose_name="لديه شهادات معتمدة"
                    ),
                ),
                (
                    "certificates_details",
                    models.TextField(blank=True, verbose_name="تفاصيل الشهادات"),
                ),
                (
                    "certificates_lost",
                    models.BooleanField(
                        default=False, verbose_name="فقد شهاداته بسبب الاعتقال/التهجير"
                    ),
                ),
                (
                    "survivor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="survivors.survivorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "وضع تعليمي",
                "verbose_name_plural": "الأوضاع التعليمية",
            },
        ),
        migrations.CreateModel(
            name="EmploymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("employed_formal", "عمل رسمي"),
                            ("employed_informal", "عمل غير رسمي"),
                            ("self_employed", "عمل حر"),
                            ("daily_labor", "عمل بالمياومة"),
                            ("unemployed_seeking", "عاطل يبحث عن عمل"),
                            ("unemployed_not_seeking", "عاطل لا يبحث"),
                            ("unable_to_work", "غير قادر على العمل (لأسباب صحية)"),
                            ("student", "طالب"),
                            ("retired", "متقاعد"),
                            ("housewife", "ربّة منزل"),
                        ],
                        max_length=30,
                        verbose_name="وضع العمل الحالي",
                    ),
                ),
                (
                    "occupation_before_detention",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="المهنة قبل الاعتقال"
                    ),
                ),
                (
                    "current_occupation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="المهنة الحالية"
                    ),
                ),
                (
                    "same_as_before",
                    models.BooleanField(
                        default=False, verbose_name="هل عاد لنفس المهنة السابقة؟"
                    ),
                ),
                (
                    "unable_due_to_health",
                    models.BooleanField(
                        default=False,
                        verbose_name="غير قادر على العمل لأسباب صحية ناتجة عن الاحتجاز",
                    ),
                ),
                (
                    "unable_due_to_legal",
                    models.BooleanField(
                        default=False,
                        verbose_name="غير قادر على العمل لأسباب قانونية (مطلوب أمنياً، فقدان وثائق...)",
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="الدخل الشهري التقريبي",
                    ),
                ),
                (
                    "income_currency",
                    models.CharField(
                        choices=[
                            ("SYP", "ليرة سورية"),
                            ("USD", "دولار أميركي"),
                            ("TRY", "ليرة تركية"),
                            ("EUR", "يورو"),
                            ("other", "أخرى"),
                        ],
                        default="SYP",
                        max_length=10,
                        verbose_name="العملة",
                    ),
                ),
                (
                    "income_covers_basic_needs",
                    models.BooleanField(
                        default=False, verbose_name="الدخل يغطي الاحتياجات الأساسية"
                    ),
                ),
                ("has_salary", models.BooleanField(default=False, verbose_name="راتب")),
                (
                    "has_business_income",
                    models.BooleanField(default=False, verbose_name="دخل من عمل تجاري"),
                ),
                (
                    "has_pension",
                    models.BooleanField(default=False, verbose_name="معاش تقاعدي"),
                ),
                (
                    "has_remittance",
                    models.BooleanField(default=False, verbose_name="حوالات من الخارج"),
                ),
                (
                    "has_humanitarian_aid",
                    models.BooleanField(default=False, verbose_name="مساعدات إنسانية"),
                ),
                (
                    "has_family_support",
                    models.BooleanField(default=False, verbose_name="مساعدات من الأهل"),
                ),
                (
                    "other_income_sources",
                    models.TextField(blank=True, verbose_name="مصادر دخل أخرى"),
                ),
                (
                    "work_hours_per_week",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ساعات العمل الأسبوعية"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "survivor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employment",
                        to="survivors.survivorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "وضع مهني ودخل",
                "verbose_name_plural": "الأوضاع المهنية والدخل",
            },
        ),
        migrations.CreateModel(
            name="HouseholdSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "أعزب/عزباء"),
                            ("married", "متزوج/ة"),
                            ("divorced", "مطلّق/ة"),
                            ("widowed", "أرمل/أرملة"),
                            ("separated", "منفصل/ة"),
                            ("engaged", "مخطوب/ة"),
                        ],
                        max_length=20,
                        verbose_name="الحالة الزوجية الحالية",
                    ),
                ),
                (
                    "marital_status_changed_due_to_detention",
                    models.BooleanField(
                        default=False,
                        verbose_name="هل تغيرت الحالة الزوجية بسبب الاعتقال؟",
                    ),
                ),
                (
                    "spouse_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الزوج/ة"
                    ),
                ),
                (
                    "spouse_alive",
                    models.BooleanField(
                        default=True, verbose_name="الزوج/ة على قيد الحياة"
                    ),
                ),
                (
                    "spouse_detained_now",
                    models.BooleanField(
                        default=False, verbose_name="الزوج/ة محتجز/ة حالياً"
                    ),
                ),
                (
                    "spouse_detained_before",
                    models.BooleanField(
                        default=False, verbose_name="الزوج/ة سبق اعتقاله/ها"
                    ),
                ),
                (
                    "spouse_employed",
                    models.BooleanField(
                        default=False, verbose_name="الزوج/ة يعمل/تعمل"
                    ),
                ),
                (
                    "spouse_occupation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عمل الزوج/ة"
                    ),
                ),
                (
                    "spouse_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="عمر الزوج/ة"
                    ),
                ),
                (
                    "household_size",
                    models.PositiveIntegerField(
                        default=1, verbose_name="إجمالي عدد أفراد الأسرة في المنزل"
                    ),
                ),
                (
                    "dependents_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المعالين كلياً"
                    ),
                ),
                (
                    "children_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الأبناء"),
                ),
                (
                    "children_count_orphaned",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="عدد الأبناء اليتامى (إن فُقد أحد الوالدين بسبب الاعتقال)",
                    ),
                ),
                (
                    "displacement_status",
                    models.CharField(
                        choices=[
                            ("not_displaced", "لم يُهجَّر"),
                            ("idp", "نازح داخلياً"),
                            ("refugee", "لاجئ خارج سوريا"),
                            ("returnee", "عائد بعد لجوء"),
                            ("asylum_seeker", "طالب لجوء"),
                        ],
                        default="not_displaced",
                        max_length=20,
                        verbose_name="وضع التهجير",
                    ),
                ),
                (
                    "displacement_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="كم مرة تم التهجير؟"
                    ),
                ),
                (
                    "original_governorate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المحافظة الأصلية"
                    ),
                ),
                (
                    "current_governorate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المحافظة/البلد الحالي"
                    ),
                ),
                ("survey_date", models.DateField(verbose_name="تاريخ المسح")),
                (
                    "survey_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="مكان المسح"
                    ),
                ),
                (
                    "survey_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الباحث"),
                ),
                (
                    "consent_to_survey",
                    models.BooleanField(
                        default=False, verbose_name="موافقة الناجي على المسح الاجتماعي"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "surveyor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_surveys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الباحث الاجتماعي",
                    ),
                ),
                (
                    "survivor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="household_survey",
                        to="survivors.survivorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "مسح اجتماعي للأسرة",
                "verbose_name_plural": "المسوحات الاجتماعية",
                "ordering": ["-survey_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_health_insurance",
                    models.BooleanField(default=False, verbose_name="لديه تأمين صحي"),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نوع التأمين"
                    ),
                ),
                (
                    "access_to_primary_care",
                    models.BooleanField(
                        default=False, verbose_name="وصول للرعاية الأولية"
                    ),
                ),
                (
                    "access_to_specialized_care",
                    models.BooleanField(
                        default=False, verbose_name="وصول للرعاية المتخصصة"
                    ),
                ),
                (
                    "distance_to_health_facility_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="بُعد أقرب مرفق صحي (كم)",
                    ),
                ),
                (
                    "chronic_illnesses_in_family",
                    models.TextField(
                        blank=True, verbose_name="الأمراض المزمنة في الأسرة"
                    ),
                ),
                (
                    "family_members_with_disability",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد ذوي الإعاقة في الأسرة"
                    ),
                ),
                (
                    "psychological_support_received",
                    models.BooleanField(
                        default=False, verbose_name="يتلقى دعماً نفسياً"
                    ),
                ),
                (
                    "psychological_support_provider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="جهة الدعم النفسي"
                    ),
                ),
                (
                    "medications_unaffordable",
                    models.BooleanField(
                        default=False, verbose_name="لا يستطيع تأمين الأدوية"
                    ),
                ),
                (
                    "unmet_medical_needs",
                    models.TextField(
                        blank=True, verbose_name="احتياجات طبية غير مُلبّاة"
                    ),
                ),
                (
                    "food_security",
                    models.CharField(
                        choices=[
                            ("good", "أمن غذائي جيد"),
                            ("moderate", "متوسط"),
                            ("poor", "ضعيف"),
                            ("severe", "انعدام أمن غذائي حاد"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="الأمن الغذائي",
                    ),
                ),
                (
                    "meals_per_day",
                    models.PositiveIntegerField(default=3, verbose_name="وجبات يومية"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_access",
                        to="social_survey.householdsurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "وصول للصحة",
                "verbose_name_plural": "بيانات الوصول للصحة",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="اسم الابن/الابنة"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="يُستخدم في حال عدم توفر تاريخ ميلاد دقيق",
                        null=True,
                        verbose_name="العمر",
                    ),
                ),
                (
                    "is_in_school",
                    models.BooleanField(
                        default=True, verbose_name="هل يداوم في المدرسة؟"
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("preschool", "روضة"),
                            ("primary", "ابتدائي"),
                            ("preparatory", "إعدادي"),
                            ("secondary", "ثانوي"),
                            ("vocational", "مهني/تقني"),
                            ("university", "جامعي"),
                            ("postgraduate", "دراسات عليا"),
                            ("not_started", "لم يبدأ الدراسة بعد"),
                            ("never_attended", "لم يلتحق بالمدرسة قطّ"),
                        ],
                        default="not_started",
                        max_length=20,
                        verbose_name="المرحلة الدراسية الحالية",
                    ),
                ),
                (
                    "current_grade",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الصف الحالي"
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم المدرسة"
                    ),
                ),
                (
                    "dropped_out",
                    models.BooleanField(default=False, verbose_name="هل ترك الدراسة؟"),
                ),
                (
                    "dropout_grade",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="الصف الذي تركها عنده"
                    ),
                ),
                (
                    "dropout_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="سنة ترك الدراسة"
                    ),
                ),
                (
                    "dropout_due_to_father_detention",
                    models.BooleanField(
                        default=False, verbose_name="ترك بسبب اعتقال الأب/الأم"
                    ),
                ),
                (
                    "dropout_reason",
                    models.TextField(blank=True, verbose_name="سبب ترك الدراسة"),
                ),
                (
                    "wants_to_resume_education",
                    models.BooleanField(
                        default=False, verbose_name="يرغب باستئناف التعليم"
                    ),
                ),
                (
                    "has_disability",
                    models.BooleanField(default=False, verbose_name="لديه إعاقة"),
                ),
                (
                    "disability_description",
                    models.TextField(blank=True, verbose_name="وصف الإعاقة"),
                ),
                (
                    "has_chronic_illness",
                    models.BooleanField(default=False, verbose_name="لديه مرض مزمن"),
                ),
                (
                    "chronic_illness_description",
                    models.TextField(blank=True, verbose_name="وصف المرض"),
                ),
                (
                    "psychological_issues",
                    models.BooleanField(
                        default=False, verbose_name="معاناة نفسية ملحوظة"
                    ),
                ),
                (
                    "psychological_notes",
                    models.TextField(
                        blank=True,
                        help_text="أعراض، تأثر باعتقال الوالد، إلخ",
                        verbose_name="ملاحظات نفسية",
                    ),
                ),
                (
                    "work_status",
                    models.CharField(
                        choices=[
                            ("student", "طالب فقط"),
                            ("helps_family", "يساعد الأسرة"),
                            ("child_labor", "عمالة أطفال"),
                            ("street_work", "عمل في الشارع"),
                            ("apprentice", "متدرّب/صبي مهنة"),
                            ("regular_job", "عمل منتظم"),
                            ("none", "لا يعمل"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="وضع العمل",
                    ),
                ),
                (
                    "work_description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="وصف العمل (إن وُجد)"
                    ),
                ),
                (
                    "work_started_due_to_detention",
                    models.BooleanField(
                        default=False, verbose_name="بدأ العمل بسبب اعتقال الوالد"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="social_survey.householdsurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "ابن/ابنة",
                "verbose_name_plural": "الأبناء",
                "ordering": ["birth_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="HousingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "housing_type",
                    models.CharField(
                        choices=[
                            ("owned", "ملك خاص"),
                            ("rented", "إيجار"),
                            ("with_family", "مع أهل/أقارب"),
                            ("shared", "سكن مشترك"),
                            ("idp_camp", "مخيم نازحين"),
                            ("refugee_camp", "مخيم لاجئين"),
                            ("shelter", "مأوى/مركز إيواء"),
                            ("damaged", "منزل متضرر"),
                            ("destroyed", "المنزل الأصلي مدمَّر"),
                            ("homeless", "بلا مأوى"),
                            ("other", "أخرى"),
                        ],
                        max_length=20,
                        verbose_name="نوع السكن",
                    ),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="قيمة الإيجار الشهري",
                    ),
                ),
                (
                    "rent_currency",
                    models.CharField(
                        choices=[
                            ("SYP", "ليرة سورية"),
                            ("USD", "دولار أميركي"),
                            ("TRY", "ليرة تركية"),
                            ("EUR", "يورو"),
                            ("other", "أخرى"),
                        ],
                        default="SYP",
                        max_length=10,
                        verbose_name="عملة الإيجار",
                    ),
                ),
                (
                    "rent_overdue",
                    models.BooleanField(default=False, verbose_name="متأخرات إيجار"),
                ),
                (
                    "rent_overdue_months",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد أشهر التأخر"
                    ),
                ),
                (
                    "threatened_with_eviction",
                    models.BooleanField(
                        default=False, verbose_name="مهدَّد بالإخراج من المنزل"
                    ),
                ),
                (
                    "rooms_count",
                    models.PositiveIntegerField(default=1, verbose_name="عدد الغرف"),
                ),
                (
                    "residents_count",
                    models.PositiveIntegerField(default=1, verbose_name="عدد القاطنين"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("good", "جيدة"),
                            ("acceptable", "مقبولة"),
                            ("poor", "سيئة"),
                            ("very_poor", "سيئة جداً/غير صالحة للسكن"),
                        ],
                        default="acceptable",
                        max_length=20,
                        verbose_name="الحالة العامة للسكن",
                    ),
                ),
                (
                    "has_electricity",
                    models.BooleanField(default=False, verbose_name="كهرباء"),
                ),
                (
                    "electricity_hours_per_day",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ساعات الكهرباء يومياً"
                    ),
                ),
                ("has_water", models.BooleanField(default=False, verbose_name="ماء")),
                (
                    "has_heating",
                    models.BooleanField(default=False, verbose_name="تدفئة"),
                ),
                (
                    "has_sanitation",
                    models.BooleanField(default=False, verbose_name="صرف صحي"),
                ),
                (
                    "has_internet",
                    models.BooleanField(default=False, verbose_name="إنترنت"),
                ),
                ("address", models.TextField(blank=True, verbose_name="العنوان")),
                (
                    "governorate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المحافظة"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة/البلدة"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=100, verbose_name="الحي"),
                ),
                (
                    "owned_original_home_before",
                    models.BooleanField(
                        default=False,
                        verbose_name="هل كان يملك منزلاً قبل الاعتقال/التهجير؟",
                    ),
                ),
                (
                    "original_home_status",
                    models.TextField(
                        blank=True, verbose_name="وضع المنزل الأصلي حالياً"
                    ),
                ),
                (
                    "property_confiscated",
                    models.BooleanField(
                        default=False, verbose_name="هل تمت مصادرة ممتلكاته؟"
                    ),
                ),
                (
                    "confiscation_details",
                    models.TextField(blank=True, verbose_name="تفاصيل المصادرة"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="housing",
                        to="social_survey.householdsurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "سكن",
                "verbose_name_plural": "معلومات السكن",
            },
        ),
        migrations.CreateModel(
            name="NeedsAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "financial_aid_priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج/طارئ"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                            ("none", "لا حاجة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="مساعدة مالية",
                    ),
                ),
                (
                    "food_aid_priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج/طارئ"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                            ("none", "لا حاجة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="مساعدة غذائية",
                    ),
                ),
                (
                    "housing_aid_priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج/طارئ"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                            ("none", "لا حاجة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="مساعدة إسكان",
                    ),
                ),
                (
                    "medical_aid_priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج/طارئ"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                            ("none", "لا حاجة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="مساعدة طبية",
                    ),
                ),
                (
                    "psychological_support_priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج/طارئ"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                            ("none", "لا حاجة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="دعم نفسي",
                    ),
                ),
                (
                    "legal_aid_priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج/طارئ"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                            ("none", "لا حاجة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="مساعدة قانونية",
                    ),
                ),
                (
                    "education_aid_priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج/طارئ"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                            ("none", "لا حاجة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="دعم تعليمي للأبناء",
                    ),
                ),
                (
                    "vocational_training_priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج/طارئ"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                            ("none", "لا حاجة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="تدريب مهني",
                    ),
                ),
                (
                    "documents_recovery_priority",
                    models.CharField(
                        choices=[
                            ("critical", "حرج/طارئ"),
                            ("high", "عالي"),
                            ("medium", "متوسط"),
                            ("low", "منخفض"),
                            ("none", "لا حاجة"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="استرداد وثائق رسمية",
                    ),
                ),
                (
                    "needs_id_card",
                    models.BooleanField(default=False, verbose_name="يحتاج هوية شخصية"),
                ),
                (
                    "needs_family_booklet",
                    models.BooleanField(default=False, verbose_name="يحتاج دفتر عائلة"),
                ),
                (
                    "needs_passport",
                    models.BooleanField(default=False, verbose_name="يحتاج جواز سفر"),
                ),
                (
                    "needs_birth_certificate",
                    models.BooleanField(
                        default=False, verbose_name="يحتاج شهادة ميلاد"
                    ),
                ),
                (
                    "needs_marriage_certificate",
                    models.BooleanField(default=False, verbose_name="يحتاج وثيقة زواج"),
                ),
                (
                    "needs_security_clearance",
                    models.BooleanField(
                        default=False, verbose_name="يحتاج إخراج قيد/تسوية وضع أمني"
                    ),
                ),
                (
                    "additional_needs",
                    models.TextField(blank=True, verbose_name="احتياجات أخرى"),
                ),
                (
                    "barriers_to_aid",
                    models.TextField(blank=True, verbose_name="عقبات الوصول للمساعدات"),
                ),
                ("assessment_date", models.DateField(verbose_name="تاريخ التقييم")),
                (
                    "follow_up_required",
                    models.BooleanField(default=True, verbose_name="يحتاج متابعة"),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ المتابعة"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "assessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المُقيِّم",
                    ),
                ),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needs",
                        to="social_survey.householdsurvey",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقييم احتياجات",
                "verbose_name_plural": "تقييمات الاحتياجات",
                "ordering": ["-assessment_date"],
            },
        ),
    ]
