# Generated by Django 5.2.14 on 2026-05-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_survey", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="householdsurvey",
            name="children_count_orphaned",
        ),
    ]
