# Generated by Django 5.2.14 on 2026-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_survey", "0002_remove_householdsurvey_children_count_orphaned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employmentinfo",
            name="occupation_before_detention",
        ),
        migrations.AlterField(
            model_name="householdsurvey",
            name="current_governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("damascus", "دمشق"),
                    ("rural_damascus", "ريف دمشق"),
                    ("aleppo", "حلب"),
                    ("homs", "حمص"),
                    ("hama", "حماة"),
                    ("latakia", "اللاذقية"),
                    ("tartus", "طرطوس"),
                    ("idlib", "إدلب"),
                    ("daraa", "درعا"),
                    ("suwayda", "السويداء"),
                    ("quneitra", "القنيطرة"),
                    ("raqqa", "الرقة"),
                    ("deir_ez_zor", "دير الزور"),
                    ("hasakah", "الحسكة"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="المحافظة الحالية (داخل سوريا)",
            ),
        ),
        migrations.AlterField(
            model_name="householdsurvey",
            name="original_governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("damascus", "دمشق"),
                    ("rural_damascus", "ريف دمشق"),
                    ("aleppo", "حلب"),
                    ("homs", "حمص"),
                    ("hama", "حماة"),
                    ("latakia", "اللاذقية"),
                    ("tartus", "طرطوس"),
                    ("idlib", "إدلب"),
                    ("daraa", "درعا"),
                    ("suwayda", "السويداء"),
                    ("quneitra", "القنيطرة"),
                    ("raqqa", "الرقة"),
                    ("deir_ez_zor", "دير الزور"),
                    ("hasakah", "الحسكة"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="المحافظة الأصلية",
            ),
        ),
        migrations.AlterField(
            model_name="housinginfo",
            name="governorate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("damascus", "دمشق"),
                    ("rural_damascus", "ريف دمشق"),
                    ("aleppo", "حلب"),
                    ("homs", "حمص"),
                    ("hama", "حماة"),
                    ("latakia", "اللاذقية"),
                    ("tartus", "طرطوس"),
                    ("idlib", "إدلب"),
                    ("daraa", "درعا"),
                    ("suwayda", "السويداء"),
                    ("quneitra", "القنيطرة"),
                    ("raqqa", "الرقة"),
                    ("deir_ez_zor", "دير الزور"),
                    ("hasakah", "الحسكة"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="المحافظة",
            ),
        ),
    ]
