# Generated by Django 5.2.14 on 2026-05-18 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorialProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lesson_id",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="معرّف الدرس"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الإكمال"
                    ),
                ),
                (
                    "quiz_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="درجة الاختبار"
                    ),
                ),
                (
                    "quiz_max",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="الحد الأقصى للاختبار"
                    ),
                ),
                ("last_visited_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorial_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تقدّم درس",
                "verbose_name_plural": "تقدّم الدروس",
                "ordering": ["user", "lesson_id"],
                "unique_together": {("user", "lesson_id")},
            },
        ),
    ]
